# result
---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: result-service
  selector:
    app: result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: kamenevlabs.azurecr.io/voting-app/result:1.0
        ports:
        - containerPort: 80
          name: result
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: dbhost
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: dbpassword
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: dbuser

# vote
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    apps: vote
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: vote-service
  selector:
    app: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: kamenevlabs.azurecr.io/voting-app/vote:1.0
        ports:
        - containerPort: 80
          name: vote
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: redishost
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: redispass

# worker
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: worker
  name: worker
spec: 
  clusterIP: None
  selector: 
    app: worker
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: worker
  name: worker
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template: 
    metadata: 
      labels: 
        app: worker
    spec: 
      containers: 
      - image: kamenevlabs.azurecr.io/voting-app/worker:1.0
        name: worker
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: redishost
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: redispass
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: dbhost
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: dbpassword
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: dbuser