apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "genaks"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "genaks"
    spec:
      containers:
        - name: "genaks"
          image: "kamenevlabs.azurecr.io/genaks"
          ports:
          - containerPort: 80