name: Build and Push docker images
on: [push]
jobs:
  build:
    name: Docker login, build, and push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.SP_APP_ID }}
          # Container registry password
          password: ${{ secrets.SP_PASSWD }}
          # Container registry server url
          login-server: ${{ secrets.ACR_URL }}

      - name: Docker Build result app
        run: docker build -f result/Dockerfile -t azurevote.azurecr/result:$GITHUB_SHA result

      - name: Docker Build vote app
        run: docker build -f vote/Dockerfile -t azurevote.azurecr/vote:$GITHUB_SHA vote

      - name: Docker Build worker app
        run: docker build -f worker/Dockerfile -t azurevote.azurecr/worker:$GITHUB_SHA worker

      - name: Docker Push result app
        run: docker push azurevote.azurecr/result:$GITHUB_SHA

      - name: Docker Push vote app
        run: docker push azurevote.azurecr/vote:$GITHUB_SHA

      - name: Docker Push worker app
        run: docker push azurevote.azurecr/worker:$GITHUB_SHA

        
