name: Build and Push docker images
on: [push]
jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.SP_APP_ID }}
          # Container registry password
          password: ${{ secrets.SP_PASSWD }}
          # Container registry server url
          login-server: ${{ secrets.ACR_URL }}

      - name: Docker Build result app
        run: docker build -f result/Dockerfile -t azurevote.azurecr/result:testtag result

        
